<footer class="site-footer custom-border-top">
   <div class="container">
      <div class="row">
         
         <div class="col-lg-6 col-md-6 mb-5 mb-lg-0">
           
               <div >
                  <h3 class="footer-heading mb-4">Quick Links</h3>
               </div>
               <div >
                  <ul class="list-unstyled">
                     <li><a href="#">Sell online</a></li>
                     <li><a href="#">Features</a></li>
                     <li><a href="#">Shopping cart</a></li>
                     <li><a href="#">Store builder</a></li>
                  </ul>
               </div>
         </div>
         <div class="col-md-6 col-lg-6">
            <div class="block-5 mb-5">
               <h3 class="footer-heading mb-4">Contact Info</h3>
               <ul class="list-unstyled">
                  <li class="address">203 Fake St. Mountain View, San Francisco, California, USA</li>
                  <li class="phone"><a href="tel://23923929210">+2 392 3929 210</a></li>
                  <li class="email"><a href="mailto:tuomas@colis.shop">emailaddress@domain.com</a></li>
               </ul>
            </div>
            <div class="block-7">
                

                <form 
                    class="form subscribe"
                    novalidate
                    action="<?= $block->escapeUrl($this->getUrl('newsletter/subscriber/new', ['_secure' => true])) ?>"
                    method="post"
                    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                    id="newsletter-validate-detail">
                    <?php echo $block->getBlockHtml('formkey')?>
                  <label for="email_subscribe" class="footer-heading">Subscribe</label>
                  <div class="form-group">
                    <input type="submit" class="btn btn-sm btn-primary" value="Send" style="top:24px;">
                    <input class="form-control py-4" name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtmlAttr(__('Enter your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    <div for="newsletter" generated="true" class="mage-error" id="newsletter-error"><span></span></div>
                     
                  </div>
               </form>
            </div>
         </div>
      </div>
      <div class="row pt-5 mt-5 text-center">
         <div class="col-md-12">
            <p>
               <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
               Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" class="text-primary">Colorlib</a>
               <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
            </p>
         </div>
      </div>
   </div>
</footer>