<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php

/**
*  General template for displaying group of blocks devided into sections
*/

$group = $block->getGroupName();
$groupCss = $block->getGroupCss();
$groupBehavior = $block->getGroupBehaviour() ? $block->getGroupBehaviour() : '{"tabs":{"openedState":"active"}}';
?>
<?php if ($detailedInfoGroup = $block->getGroupChildNames($group, 'getChildHtml')):?>
    <div class="horizontal-menu desktop hidden-xs">
        <div class="header-horizontal-menu" style="text-transform: capitalize;">
        <?php $layout = $block->getLayout(); ?>
        
            <?php foreach ($detailedInfoGroup as $name):?>
                <?php                
                    $html = $layout->renderElement($name);
                    if (!trim($html) && ($block->getUseForce() != true)) {
                        continue;
                    }                   
                ?>                
                <?= /* @escapeNotVerified */ $html ?>
            <?php endforeach;?>
        </div>
    </div>
<?php endif; ?>
