<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>


    <ul class="items">
    	<li class="level0 level-top ui-menu-item">
		    <a href="<?php echo $this->getBaseUrl(); ?>" class="level-top ui-corner-all"  role="menuitem">
		        <span><?= __("Home")?></span>
		    </a>
		</li>
        <?= /* @escapeNotVerified */ $_menu ?>   
        <li class="level0 level-top ui-menu-item">
		    <a href="<?php echo $this->getBaseUrl()."about-us"; ?>" class="level-top ui-corner-all"  role="menuitem">
		        <span><?= __("About Us")?></span>
		    </a>
		</li>   
		<li class="level0 level-top ui-menu-item">
		    <a href="<?php echo $this->getBaseUrl()."contact-us"; ?>" class="level-top ui-corner-all"  role="menuitem">
		        <span><?= __("Contact Us")?></span>
		    </a>
		</li>     
    </ul>

