
<?php $storeName = $block->getThemeName() ? $block->getThemeName() : $block->getLogoAlt();?>
<li class="nav item logolink">
   <!-- <a class="logo" href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
       <img src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
            alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
            <?php echo $block->getLogoWidth() ? 'width="' . $block->getLogoWidth() . '"' : '' ?>
            <?php echo $block->getLogoHeight() ? 'height="' . $block->getLogoHeight() . '"' : '' ?>
       />
</a> -->
	<a href="<?php echo $block->getUrl(''); ?>" title="<?php /* @escapeNotVerified */ echo $storeName ?>">
		 <img class="imagelogo" src="<?php /* @escapeNotVerified */ echo $block->getLogoSrc() ?>"
            alt="<?php /* @escapeNotVerified */ echo $block->getLogoAlt() ?>"
            style="<?php echo $block->getLogoHeight() ? 'height:' . $block->getLogoHeight() . 'px' : '' ?>" />
         <img class="imagelogomobile" src="<?php echo $block->getViewFileUrl('images/logo-small.png'); ?>" />
            
	</a>
</li>
<li class="nav item logolink">
	<a href="/about-us"><span class="icolinktext icon-user"></span> <span class="logotext linktext"><?=__("About Us")?></span></a>
</li>
<li class="nav item logolink mobileshow">
	<a href="/contact-us"><span class="icolinktext icon-contact_mail"> </span><span class="logotext linktext"><?=__("Contact Us")?></span></a>
</li>
<li class="nav item logolink mobileshow">
  <a href="http://deven.colishelsinki.com"><span class="icolinktext"><?=__("EN")?> </span><span class="logotext linktext"><?=__("English")?></span></a>
</li>
<li class="nav item logolink mobileshow">
  <a href="http://dev.colishelsinki.com"><span class="icolinktext"><?=__("FI")?> </span><span class="logotext linktext"><?=__("Finnish")?></span></a>
</li>