<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <!-- <select id="sorter" data-role="sorter" class="sorter-options"> -->
      <button type="button" class="btn btn-white btn-sm dropdown-toggle px-4" id="dropdownMenuReference" data-toggle="dropdown"><?=$block->getCurrentOrder()?></button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuReference">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
          <a class="dropdown-item" href="?product_list_order=<?= $block->escapeHtmlAttr($_key) ?>"><?= $block->escapeHtml(__($_order)) ?></a>
          
        <?php endforeach; ?>
      </div>
    <!-- </select> -->
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
